language: python
os:
    - "linux"
env:
    - NODE_VERSION="7.5"
    # - NODE_VERSION="7.3"
    # - NODE_VERSION="7.2"
    # - NODE_VERSION="7.1"
    # - NODE_VERSION="7.0"
    - NODE_VERSION="6.1"
    # - NODE_VERSION="6.0"
    - NODE_VERSION="5.11"
    # - NODE_VERSION="5.10"
    # - NODE_VERSION="5.9"
    # - NODE_VERSION="5.8"
    # - NODE_VERSION="5.7"
    # - NODE_VERSION="5.6"
    # - NODE_VERSION="5.5"
    # - NODE_VERSION="5.4"
    # - NODE_VERSION="5.3"
    # - NODE_VERSION="5.2"
    # - NODE_VERSION="5.1"
    # - NODE_VERSION="5.0"
    - NODE_VERSION="4.4"
    # - NODE_VERSION="4.3"
    # - NODE_VERSION="4.2"
    # - NODE_VERSION="4.1"
    # - NODE_VERSION="4.0"
python:
    - "nightly"
    - "3.5"
    - "3.4"
    - "3.3"
    - "3.2"
    - "2.7"
    - "2.6"
before_install:
    - rm -rf ~/.nvm
    - git clone https://github.com/creationix/nvm.git ~/.nvm
    - source ~/.nvm/nvm.sh
    - nvm install $NODE_VERSION
install:
    - npm install
before_script:
    - python -V
    - node --version
script:
    npm test
cache:
  directories:
    - node_modules
