language: python
os:
    - "linux"
env:
    - NODE_VERSION="11"
    - NODE_VERSION="10"
    - NODE_VERSION="9"
    - NODE_VERSION="8"
    - NODE_VERSION="7.5"
    - NODE_VERSION="6.1"
    - NODE_VERSION="5.11"
    - NODE_VERSION="4.4"
python:
    - "3.7-dev"
    - "3.6"
    - "3.5"
    - "3.4"
    - "3.3"
    - "3.2"
    - "2.7"
    - "2.6"
before_install:
    - rm -rf ~/.nvm
    - git clone https://github.com/creationix/nvm.git ~/.nvm
    - source ~/.nvm/nvm.sh
    - nvm install $NODE_VERSION
install:
    - npm install -d
before_script:
    - python -V
    - node --version
script:
    npm test
cache:
  directories:
    - node_modules
